version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: nest-crud
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: nest-crud
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres-data:/var/lib/postgresql/data


volumes:
  postgres-data:



